name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: make all
      - name: Set up gotestfmt
        uses: haveyoudebuggedit/gotestfmt-action@v2
      - name: Run unit tests
        run: |
          set -euo pipefail
          go test -v ./...
